"""Pydantic v2 data models for emergency incident analysis.

These are the output models from Gemini's reasoning layer.
All output from Gemini is validated against these schemas
BEFORE any action is taken (safety gate).
"""

from __future__ import annotations

from datetime import datetime
from enum import Enum
from typing import Literal, Optional

from pydantic import BaseModel, Field, field_validator


class TriageLevel(str, Enum):
    """Clinical triage classification.

    Each level maps to a specific response protocol:
    - CRITICAL: Send FHIR brief to hospital, call 108 immediately
    - URGENT: See doctor within 2 hours
    - MODERATE: GP visit today
    - STABLE: Routine management, monitor
    - CALL_108: Uncertainty-triggered safety fallback
    """

    CRITICAL = "CRITICAL"
    URGENT = "URGENT"
    MODERATE = "MODERATE"
    STABLE = "STABLE"
    CALL_108_IMMEDIATELY = "CALL_108"


class ActionStep(BaseModel):
    """Single step in the caregiver guidance sequence.

    Steps are written in plain, non-medical language.
    A caregiver with no medical training must be able to follow each step.
    """

    priority: int = Field(ge=1, le=10, description="Execution order (1 = first)")
    instruction: str = Field(
        min_length=10,
        max_length=300,
        description="Plain-language instruction for the caregiver",
    )
    caution: Optional[str] = Field(
        default=None,
        max_length=200,
        description="Warning or contraindication relevant to this step",
    )
    rationale: str = Field(
        min_length=5,
        max_length=400,
        description="Why this step — tied to patient history (not shown to caregiver)",
    )


class DrugFlag(BaseModel):
    """Drug interaction or contraindication flag.

    Generated by cross-referencing the detected emergency with the
    patient's active medication list.
    """

    drug_name: str = Field(min_length=1, max_length=200)
    flag_type: Literal["DO_NOT_REPEAT", "INTERACTION", "CONTRAINDICATED", "INFO"]
    explanation: str = Field(
        min_length=10,
        max_length=500,
        description="Plain-language explanation of the flag",
    )


class EmergencyAnalysis(BaseModel):
    """Structured output from a single Gemini emergency reasoning call.

    This model IS the contract between the AI and the application.
    Every field is required — Gemini is prompted to return all fields.
    The safety validator gate checks this model before any action is taken.
    """

    detected_language: str = Field(
        description="BCP-47 language code detected in input (e.g., 'hi', 'ta', 'kn')"
    )
    triage_level: TriageLevel
    primary_concern: str = Field(
        min_length=3,
        max_length=300,
        description="One-line clinical summary of the primary emergency",
    )
    confidence: float = Field(
        ge=0.0,
        le=1.0,
        description="Gemini's confidence in this assessment (0.0–1.0)",
    )
    patient_summary: str = Field(
        min_length=10,
        max_length=500,
        description="Brief summary of relevant patient context used in this assessment",
    )
    chief_complaint: str = Field(
        min_length=3,
        max_length=300,
        description="Clinical chief complaint as would appear in an ER triage note",
    )
    drug_flags: list[DrugFlag] = Field(
        default_factory=list,
        description="Drug interactions or contraindications relevant to this emergency",
    )
    caregiver_steps: list[ActionStep] = Field(
        min_length=1,
        description="Ordered guidance steps for the caregiver (must be at least 1)",
    )
    hospital_brief: str = Field(
        min_length=20,
        max_length=1000,
        description="Complete clinical brief for the hospital ER physician",
    )
    fhir_trigger: bool = Field(
        description="True if a FHIR R4 bundle should be sent to the hospital immediately",
    )
    incident_id: Optional[str] = Field(
        default=None,
        description="Assigned after saving to Firestore",
    )
    analyzed_at: datetime = Field(default_factory=datetime.utcnow)

    @field_validator("caregiver_steps")
    @classmethod
    def steps_must_be_ordered(cls, v: list[ActionStep]) -> list[ActionStep]:
        """Steps must be in strict priority order 1, 2, 3..."""
        priorities = [s.priority for s in v]
        if priorities != sorted(priorities):
            raise ValueError(
                f"caregiver_steps must be in ascending priority order. Got: {priorities}"
            )
        if len(set(priorities)) != len(priorities):
            raise ValueError("caregiver_steps must have unique priority values")
        return v

    @field_validator("confidence")
    @classmethod
    def confidence_precision(cls, v: float) -> float:
        """Round to 2 decimal places for consistency."""
        return round(v, 2)


class EmergencyRequest(BaseModel):
    """HTTP request model for POST /emergency/analyze."""

    patient_id: str = Field(min_length=1, description="Patient's Firestore document ID")
    transcript: Optional[str] = Field(
        default=None,
        max_length=5000,
        description="Transcribed voice input (from STT or typed)",
    )
    ocr_text: Optional[str] = Field(
        default=None,
        max_length=3000,
        description="Text extracted from prescription/document photo",
    )
    vitals_json: Optional[dict] = Field(
        default=None,
        description="Raw vitals reading from IoT wearable",
    )
    image_base64: Optional[str] = Field(
        default=None,
        description="Base64-encoded prescription/discharge photo for OCR",
    )
    source_language: Optional[str] = Field(
        default=None,
        description="Override detected language (BCP-47 code)",
    )

    @field_validator("*", mode="before")
    @classmethod
    def at_least_one_input(cls, v: object) -> object:
        """Validated at model level — at least transcript, ocr_text, or vitals_json."""
        return v

    def has_any_input(self) -> bool:
        """Return True if at least one input modality is provided."""
        return any([self.transcript, self.ocr_text, self.vitals_json, self.image_base64])


class EmergencyResponse(BaseModel):
    """HTTP response model for POST /emergency/analyze."""

    incident_id: str
    triage_level: TriageLevel
    primary_concern: str
    caregiver_steps: list[ActionStep]
    drug_flags: list[DrugFlag]
    hospital_notified: bool
    detected_language: str
    response_language: str
    analyzed_at: datetime


class IncidentSummary(BaseModel):
    """Lightweight incident summary for history listing."""

    incident_id: str
    patient_id: str
    triage_level: TriageLevel
    primary_concern: str
    analyzed_at: datetime
    hospital_notified: bool
